# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Son < Formula
  desc "Developer workspace launcher — open the right repo in the right workspace"
  homepage "https://github.com/abdussamet032/son"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdussamet032/son/releases/download/v1.3.0/son_1.3.0_darwin_amd64.tar.gz"
      sha256 "c09902f837964f56afe21a08c7441e491c65c3734b8b0aa5343ddcf23b51dd37"

      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdussamet032/son/releases/download/v1.3.0/son_1.3.0_darwin_arm64.tar.gz"
      sha256 "032e6b29f1867d536a8cc953a4a956f5dc7b8dd4a2d93a2122463d305dd71ee0"

      define_method(:install) do
        bin.install "son"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.3.0/son_1.3.0_linux_amd64.tar.gz"
      sha256 "d858cf4bcf6902d65fee3ca1c625a7c50c955b88b36a557f67439c60de09906a"
      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.3.0/son_1.3.0_linux_arm64.tar.gz"
      sha256 "b6f7427d1899c0ce720a91626e88b5d9765c269e3c1869c4d6d65374bd4c1dee"
      define_method(:install) do
        bin.install "son"
      end
    end
  end

  test do
    system "#{bin}/son", "version"
  end
end
