# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Son < Formula
  desc "Developer workspace launcher — open the right repo in the right workspace"
  homepage "https://github.com/abdussamet032/son"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdussamet032/son/releases/download/v1.1.0/son_1.1.0_darwin_amd64.tar.gz"
      sha256 "1ee20b5e5f9c6e7f6bc95eee8033b15975b20a5fef1039a601add0da733e3a19"

      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdussamet032/son/releases/download/v1.1.0/son_1.1.0_darwin_arm64.tar.gz"
      sha256 "dbfcbdda96717e78f5ee913040abb2ce9949219b41fd56a470f7d7c94434c514"

      define_method(:install) do
        bin.install "son"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.1.0/son_1.1.0_linux_amd64.tar.gz"
      sha256 "e10ba70eaf7e85aa3ddd640ca9124e4291cc03b6c7bfd92e89148603460b8fe3"
      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.1.0/son_1.1.0_linux_arm64.tar.gz"
      sha256 "f8a4df0a930f6232e0c7e891c62409bdc3839f95a2fbc49f0725afad61d02ab0"
      define_method(:install) do
        bin.install "son"
      end
    end
  end

  test do
    system "#{bin}/son", "version"
  end
end
