# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Son < Formula
  desc "Developer workspace launcher — open the right repo in the right workspace"
  homepage "https://github.com/abdussamet032/son"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdussamet032/son/releases/download/v1.2.1/son_1.2.1_darwin_amd64.tar.gz"
      sha256 "5c88b1e6b7264d144daf621c50e88d328b4f680a8e85ed50efa5f9106cfa788c"

      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdussamet032/son/releases/download/v1.2.1/son_1.2.1_darwin_arm64.tar.gz"
      sha256 "0d6312fa45608c319a72cb05963f0cbcf5342c861893318b44cb85ba8bd1ec55"

      define_method(:install) do
        bin.install "son"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.2.1/son_1.2.1_linux_amd64.tar.gz"
      sha256 "12d12c2d2449c9abaf0bcb36246c6272c282519c8cd9807514bb13dfde452734"
      define_method(:install) do
        bin.install "son"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdussamet032/son/releases/download/v1.2.1/son_1.2.1_linux_arm64.tar.gz"
      sha256 "dd17d7f4f1e36b3395ecedb7897b0dbdde52144ebf7e59622fad2b2e96735dda"
      define_method(:install) do
        bin.install "son"
      end
    end
  end

  test do
    system "#{bin}/son", "version"
  end
end
